name = "discord-auto-delete"
main = "src/worker.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
preview_urls = false

[[kv_namespaces]]
binding = "CONFIGS_KV"
id = "94d5f54ab59c488bb0a4d3e8d3f3dca1"
preview_id = "a0a0c46e2f83417d85837c591ee33f10"

[triggers]
crons = ["0 * * * *"]
